name: 'Run Tests'
description: 'Runs test suite with optional build artifacts'

inputs:
  test-type:
    description: 'Type of tests to run (unit, e2e, policy, all)'
    required: true
  download-build:
    description: 'Whether to download build artifacts'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Download build artifacts
      if: inputs.download-build == 'true'
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/
    
    - name: Run Unit Tests
      if: inputs.test-type == 'unit' || inputs.test-type == 'all'
      shell: bash
      run: npm test
    
    - name: Run Policy Check
      if: inputs.test-type == 'policy' || inputs.test-type == 'all'
      shell: bash
      run: npm run policy:check
    
    - name: Run E2E Tests
      if: inputs.test-type == 'e2e' || inputs.test-type == 'all'
      shell: bash
      run: npm run test:e2e
      env:
        CI: true
    
    - name: Upload Playwright Report
      if: failure() && (inputs.test-type == 'e2e' || inputs.test-type == 'all')
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ github.sha }}
        path: playwright-report/
        retention-days: 7
        compression-level: 9
